import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { BookOpen, FileText, ExternalLink } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const Resources = () => {
  const frameworks = [
    {
      name: "GHG Protocol",
      description: "The most widely used greenhouse gas accounting standard",
      url: "https://ghgprotocol.org/"
    },
    {
      name: "GRI Standards",
      description: "Global Reporting Initiative sustainability reporting standards",
      url: "https://www.globalreporting.org/"
    },
    {
      name: "SASB Standards",
      description: "Sustainability Accounting Standards Board industry-specific standards",
      url: "https://www.sasb.org/"
    },
    {
      name: "ISO 14064",
      description: "International standard for GHG quantification and reporting",
      url: "https://www.iso.org/"
    },
    {
      name: "UN SDGs",
      description: "United Nations Sustainable Development Goals alignment",
      url: "https://sdgs.un.org/"
    }
  ];

  const glossary = [
    {
      term: "Scope 1 Emissions",
      definition: "Direct greenhouse gas emissions from sources owned or controlled by your organization (e.g., company vehicles, on-site fuel combustion)."
    },
    {
      term: "Scope 2 Emissions",
      definition: "Indirect emissions from the generation of purchased electricity, steam, heating, and cooling consumed by your organization."
    },
    {
      term: "Scope 3 Emissions",
      definition: "All other indirect emissions in your value chain, including business travel, employee commuting, purchased goods, waste, and transportation."
    },
    {
      term: "Carbon Footprint",
      definition: "The total amount of greenhouse gases (measured in CO₂ equivalents) generated by an organization, product, or activity."
    },
    {
      term: "ESG",
      definition: "Environmental, Social, and Governance—a framework for evaluating an organization's sustainability and ethical impact."
    },
    {
      term: "GWP (Global Warming Potential)",
      definition: "A measure of how much heat a greenhouse gas traps in the atmosphere compared to carbon dioxide over a specific time period."
    },
    {
      term: "Emission Factor",
      definition: "A coefficient that quantifies the emissions per unit of activity (e.g., kg CO₂ per kWh of electricity or per gallon of fuel)."
    },
    {
      term: "Carbon Neutrality",
      definition: "Achieving net-zero carbon emissions by balancing emissions with carbon removal or offsets."
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="pt-24 pb-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-accent/10 rounded-2xl mb-6">
              <BookOpen className="w-8 h-8 text-accent" />
            </div>
            <h1 className="text-4xl font-bold mb-4 text-foreground">Resources & Documentation</h1>
            <p className="text-lg text-muted-foreground">
              Learn about our methodologies, standards, and sustainability frameworks.
            </p>
          </div>

          {/* Methodologies */}
          <section id="methodology" className="mb-16">
            <h2 className="text-2xl font-bold mb-6 text-foreground">Methodologies</h2>
            <Card className="border-border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="w-5 h-5 text-primary" />
                  Calculation Transparency
                </CardTitle>
                <CardDescription>
                  All our tools follow internationally recognized standards and provide full visibility into calculations.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2 text-foreground">ESG Assessment Methodology</h3>
                  <p className="text-sm text-muted-foreground mb-2">
                    Our ESG scoring uses a proprietary algorithm based on international standards (SASB, GRI, TCFD). Each organization is evaluated on a 0-100 scale across three pillars:
                  </p>
                  <ul className="text-sm text-muted-foreground space-y-2 ml-4 mb-4">
                    <li>
                      <span className="font-medium text-foreground">Environmental (E):</span> Assesses climate impact, resource efficiency, and ecological stewardship.
                      <ul className="ml-4 mt-1 list-disc">
                        <li>GHG Emissions (Scope 1, 2, 3)</li>
                        <li>Energy Management & Renewables</li>
                        <li>Water & Waste Management</li>
                        <li>Biodiversity & Compliance</li>
                      </ul>
                    </li>
                    <li>
                      <span className="font-medium text-foreground">Social (S):</span> Evaluates relationships with employees, suppliers, customers, and communities.
                      <ul className="ml-4 mt-1 list-disc">
                        <li>Workforce Health & Safety</li>
                        <li>Diversity, Equity & Inclusion (DEI)</li>
                        <li>Labor Practices & Human Rights</li>
                        <li>Community Impact & Product Responsibility</li>
                      </ul>
                    </li>
                    <li>
                      <span className="font-medium text-foreground">Governance (G):</span> Measures leadership accountability, ethics, and transparency.
                      <ul className="ml-4 mt-1 list-disc">
                        <li>Board Structure & Independence</li>
                        <li>Executive Compensation & Incentives</li>
                        <li>Business Ethics & Compliance</li>
                        <li>Risk Management & Transparency</li>
                      </ul>
                    </li>
                  </ul>
                  <p className="text-sm text-muted-foreground">
                    <span className="font-medium text-foreground">Sector-Specific Weighting:</span> Scores are adjusted based on the materiality of each pillar for your specific industry sector, ensuring relevance and accuracy.
                  </p>
                </div>
                <div>
                  <h3 className="font-semibold mb-2 text-foreground">Emissions Calculation Methodology</h3>
                  <p className="text-sm text-muted-foreground mb-2">
                    We follow the GHG Protocol Corporate Standard for all emission calculations. Emission factors are sourced from:
                  </p>
                  <ul className="text-sm text-muted-foreground space-y-1 ml-4">
                    <li>• IPCC Assessment Reports</li>
                    <li>• EPA Emission Factors</li>
                    <li>• Regional grid factors (location-based)</li>
                    <li>• Industry-specific databases</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold mb-2 text-foreground">Footprint Calculation Methodology</h3>
                  <p className="text-sm text-muted-foreground">
                    Sector-specific calculations use detailed emission factors for materials, processes, and activities unique to each industry. All factors are referenced and traceable to original sources.
                  </p>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Standards & Frameworks */}
          <section id="standards" className="mb-16">
            <h2 className="text-2xl font-bold mb-6 text-foreground">Standards & Frameworks</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {frameworks.map((framework, index) => (
                <Card key={index} className="border-border hover:shadow-md transition-shadow">
                  <CardContent className="pt-6">
                    <h3 className="font-semibold mb-2 text-foreground">{framework.name}</h3>
                    <p className="text-sm text-muted-foreground mb-3">{framework.description}</p>
                    <a
                      href={framework.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-sm text-primary hover:text-primary-light flex items-center gap-1 transition-colors"
                    >
                      Learn more
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </CardContent>
                </Card>
              ))}
            </div>
          </section>

          {/* Glossary */}
          <section id="glossary" className="mb-16">
            <h2 className="text-2xl font-bold mb-6 text-foreground">Glossary</h2>
            <Card className="border-border">
              <CardContent className="pt-6">
                <Accordion type="single" collapsible className="w-full">
                  {glossary.map((item, index) => (
                    <AccordionItem key={index} value={`item-${index}`}>
                      <AccordionTrigger className="text-left font-semibold text-foreground">
                        {item.term}
                      </AccordionTrigger>
                      <AccordionContent className="text-sm text-muted-foreground">
                        {item.definition}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Resources;
